elasticsearch:
  image: elasticsearch:latest
  container_name: elasticsearch
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"

logstash:
  image: logstash:latest
  container_name: logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /var/log/eapi:/var/log/eapi
  ports:
    - "5000:5000"
  links:
    - elasticsearch

kibana:
  build: kibana/
  container_name: kibana
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
